#--- Color ---#
RED='\033[0;31m'
PINK='\033[95m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BLUE='\033[34m'
NC='\033[0m'

#--- perror ---#
ERROR="${RED}ERROR:${NC}"
WARNING="${YELLOW}WARNING:${NC}"
SUCCESS="${GREEN}SUCCESS:${NC}"
CHOICE="${BLUE}CHOICE:${NC}"
USAGE="${BLUE}USAGE:${NC}"
HINT="${BLUE}HINT:${NC}"
ANNOUNCE="${CYAN}ANNOUNCE:${NC}"
DETECTED="${CYAN}DETECTED:${NC}"